-- Septième lot de builds fournis par le staff (18/08/2026) — voir
-- 012_best_builds.sql pour le contexte de la table.
insert into best_builds (brawler_slug, brawler_name, comment) values
  ('billie', 'Billie', 'Avec Billie, c''est tout droit garanti ! Un gadget beaucoup trop fort qu''on va rentabiliser avec l''équipement gadget accéléré, et un pouvoir star qui augmente votre vitesse et même vos dégâts. Que demander de plus ?'),
  ('bea', 'Béa', 'Béa, souvent utilisée par les cheaters de par sa grande portée et son super ralentissant les ennemis. Beaucoup de contrôle avec son gadget, et rester plus longtemps en vie avec son pouvoir star. Sa portée et son super couvrant une large zone lui donnent accès à un gear vision très efficace. Vous pouvez tout à fait équiper l''autre pouvoir star si vous jouez contre des grosses brutes sans portée, pour leur faire passer un sale quart d''heure.'),
  ('nani', 'Nani', 'Nani, des gros dégâts de près comme de loin. On joue ce build pour l''utiliser dans sa fonction première, qui est de contrer les différents snipers. Vous pouvez jouer l''autre pouvoir star en cas d''assassins adverses, pour tanker avec vos 80% de réduction. En Braquage, on jouera le pouvoir star du bouclier et le gadget de téléportation, pour aller directement mettre de gros dégâts au coffre au corps à corps. Le gear vision peut être une option si besoin.'),
  ('edgar', 'Edgar', 'Edgar, le fameux Edgar… Personnage préféré de votre cher Twisty, pas besoin de vous expliquer comment le jouer. On préférera l''équipement bouclier pour éviter de mourir sur le premier adversaire venu. Si vos ennemis prennent des personnages avec beaucoup de PV ou un faible DPS, je vous recommande l''autre pouvoir star.'),
  ('griff', 'Griff', 'Griff, l''un des tout meilleurs persos en termes de polyvalence. Ce build vous permet d''ouvrir la map le plus rapidement possible tout en vous protégeant des assassins. Si vous n''avez pas besoin d''ouvrir la map, il vous suffit de changer de gadget ; si vous voulez rester longtemps en vie, changez de pouvoir star. Niveau équipements : dégâts/gadget accéléré vont de pair, tout comme bouclier/vision ou dégâts/bouclier.'),
  ('bonnie', 'Bonnie', 'Bonnie est à jouer principalement en Braquage. Son équipement épique et son gadget vous permettent de charger le super plus rapidement, et le pouvoir star avec l''équipement bouclier permettent de faire le kamikaze sur le coffre. C''est tout pour Bonnie.'),
  ('grom', 'Grom', 'Voilà pour Grom. Un conseil pour le jouer ? Ne le jouez pas.'),
  ('gael', 'Gael', 'Un excellent perso anti-assassins et anti-tanks, ce bon vieux Gael. On le joue en mode contrôle de buissons pour empêcher les adversaires de passer, tout en adaptant les équipements à son style de jeu. La tornade vous assure une protection contre les ennemis les plus furtifs, et le pouvoir star vous permet de les agresser contre les murs.')
on conflict (brawler_slug) do nothing;
