-- Neuvième lot de builds fournis par le staff (19/08/2026) — voir
-- 012_best_builds.sql pour le contexte de la table.
insert into best_builds (brawler_slug, brawler_name, comment) values
  ('ash', 'Ash', 'Ash, le brawler préféré de… personne, car qui aime les poubelles ? Cela dit, l''habit ne fait pas le moine : ce build le transforme en un véritable monstre en map fermée. Le combo des gears dégâts et vitesse lui offre une agressivité sans pareille. Du haut de ses 12 000 PV, il peut se permettre de foncer dans le tas. Vous pouvez maximiser l''effet du gadget en l''utilisant juste après avoir lancé votre super sur les ennemis. Enfin bref, faites passer vos adversaires (ou vos bad randoms) pour des déchets, et ramassez-les.'),
  ('lola', 'Lola', 'Lola, véritable monstre de dégâts. L''un des meilleurs persos pour tenir sa ligne en map ouverte, même en présence de buissons grâce au gear vision, qu''elle exploite pleinement avec son excellente portée et ses tirs nombreux. Avec ce pouvoir star, vous pourrez tenir votre ligne encore plus facilement, en plus d''apporter du soin à vos mates. Le gadget vous permet de tanker de gros dégâts grâce au super et de temporiser plus facilement vos duels. Vous pouvez jouer l''autre pouvoir star en Braquage contre des matchups compliqués, pour les surprendre (prenez le gear dégâts avec). Petite astuce : placez votre ultime en autoshoot pour profiter du heal du pouvoir star et infliger plus de dégâts sans réfléchir.'),
  ('sam', 'Sam', 'Détesté par beaucoup (Rush, je te vois), Sam est en réalité un très bon brawler possédant des matchups très intéressants. Il ne faut pas avoir peur de mourir en le jouant : votre gameplan est de charger l''hypercharge au plus vite et de détruire l''entièreté de l''équipe adverse. Foncer droit sur les ennemis est rarement une bonne stratégie, mais ça fonctionne particulièrement bien avec Sam. Son gadget vous assure un kill, du moment que vous n''attirez pas une Shelly sous ultime. Le pouvoir star vous permet de régénérer votre vie en récupérant les gants, ce qui facilite grandement le travail. N''oubliez pas que vous régénérez aussi passivement comme tous les autres persos, donc arrêtez de spammer vos gants dans les murs, c''est inutile.'),
  ('mandy', 'Mandy', 'Le sniper pour débutants, j''ai nommé Mandy ! Bien qu''elle possède de gros dégâts, son attaque est très lente et facile à esquiver. On joue donc le pouvoir star qui augmente la vitesse des balles dans TOUS les cas, pour toucher un peu plus souvent. Le gadget tire à travers les murs et permet d''obtenir plus facilement votre super, qui est dévastateur (dédicace à Faith). N''utilisez pas votre super en début de round de Hors-jeu, ça ne fonctionnera pas sur de bons adversaires. Si vous êtes main Mandy, arrêtez et allez jouer Pierce — c''est pareil, en plus cool et beaucoup plus fort.'),
  ('maisie', 'Maisie', 'Maisie, perso utilisé uniquement par les chads, avec 3 excellents skins (regardez JoJo). Son attaque est difficile à maîtriser, mais si vous touchez vos tirs, c''est carnage assuré. Son excellent super détruira tout type d''adversaires à votre portée et les ralentira grâce au pouvoir star ; il vous suffit d''enchaîner avec 2-3 attaques plus faciles à toucher grâce au fameux ralentissement. Petite astuce bien connue : utilisez rapidement le gadget suivi du super, pour utiliser le super tout en dashant.'),
  ('hank', 'Hank', 'Hank est unique à jouer. Il peut mettre beaucoup de pression s''il avance derrière les murs. Le gear dégâts vous permettra d''infliger de très lourds dégâts (normal, c''est son nom), et le gear santé vous permet de patienter moins longtemps, car Hank ne se soigne pas en gonflant sa bulle. Astuce : jouez à 3 doigts pour pouvoir utiliser votre gadget, qui applique une réduction de dégâts tout en chargeant votre attaque — vous pourrez mettre beaucoup plus de pression. Ne visez pas la bulle si vous voulez prendre un kill : restez appuyé sur le bouton d''attaque à la place, et lâchez-le quand la bulle est pleinement chargée. Ça vous donnera un angle optimal et vous toucherez bien plus facilement.')
on conflict (brawler_slug) do nothing;
