-- Dixième lot de builds fournis par le staff (27/08/2026) — voir
-- 012_best_builds.sql pour le contexte de la table.
insert into best_builds (brawler_slug, brawler_name, comment) values
  ('pearl', 'Pearl', 'Pearl est un véritable monstre de statistiques. Elle possède énormément de vie pour sa catégorie ; ainsi, nous équipons le pouvoir star qui donne un bouclier supplémentaire, l''équipement bouclier et l''équipement dégâts pour tout renforcer. Astuce : votre super casse les murs, n''hésitez pas à l''utiliser au plus tôt si nécessaire.'),
  ('larry-lawrie', 'Larry & Lawrie', 'Pour Larry & Lawrie, on vous propose un build 100% Kama, qui surprendra forcément vos adversaires. On joue le gadget qui échange l''arme des frères : chargez un super, envoyez-le derrière un mur pour lui donner l''arme du lanceur. Vous aurez ainsi un moyen de vous défendre pendant que votre jumeau charge grandement son super. Si vous avez l''arme de Lawrie, placez un autre super et utilisez votre gadget : vous obtenez 2 lanceurs pour le prix d''un, et c''est excellent. Le pouvoir star vous permet de cycler encore plus vite vos supers, ce qui est très appréciable. N''hésitez pas à jouer l''équipement vision au besoin.'),
  ('angelo', 'Angelo', 'Avec Angelo, l''objectif est de jouer comme un moustique : restez en vie pour infliger des petites (ou grosses) piqûres à vos adversaires. On joue ce gadget pour surprendre des cibles basses en PV, ou pour charger le super facilement. Tout comme Hank, c''est l''un des meilleurs utilisateurs de l''équipement santé : son attaque doit se charger, donc on veut perdre le moins de temps possible.'),
  ('berry', 'Berry', 'Pour Berry, on joue ce build dans tous les modes sauf Braquage, où l''on utilisera l''autre pouvoir star et l''autre gadget pour détruire le coffre très facilement. Il n''a pas beaucoup de vie : faites attention.'),
  ('shade', 'Shade', 'Le gameplay de Shade est très simple : obtenez votre super en ne faisant rien ou en grattant quelques coups de gadget, puis foncez sous super avec le bouclier offert par le pouvoir star. On joue bien l''équipement gadget accéléré et pas bouclier, le gadget étant trop important pour ce personnage.'),
  ('meeple', 'Meeple', 'Meeple avec l''équipement vision est tellement fort que c''en est presque de la triche. Le personnage est très complet : les deux gadgets sont excellents, tout comme les deux pouvoirs star. On joue plutôt la boîte comme gadget, qui est un peu plus polyvalente ; l''autre est davantage utilisé en Brawlball, ou pour contrer les assassins. Choisissez vos équipements parmi les quatre achetés ci-dessus, ils sont tous très bons.'),
  ('trunk', 'Trunk', 'Trunk est probablement le tank le plus sous-coté. Il n''en reste pas moins excellent, surtout sur les maps possédant de nombreux murs et buissons, où il peut exploiter son plein potentiel. Équipements dégâts et vitesse pour jouer plus agressivement, un super qui découpe tout le monde et une attaque circulaire à la Jacky. La seule difficulté du personnage repose sur son gadget, qui peut être décisif en combat mais très difficile à bien utiliser. Il faut aussi bien se placer pour infliger un maximum de dégâts aux ennemis avec son attaque.'),
  ('bolt', 'Bolt', 'Bolt : débranchez votre cerveau et laissez-vous aller, façon conduite en état d''ivresse pour surprendre vos ennemis. On joue ce gadget pour esquiver une grosse source de dégâts et contre-attaquer. L''autre gadget est meilleur contre des ennemis avec de faibles dégâts ; dans ce cas, remplacez l''équipement santé par l''équipement gadget accéléré.')
on conflict (brawler_slug) do nothing;
