from typing import Protocol


class IndustrialEconomyRepository(Protocol):
    """Contrat synchrone exécuté hors event loop par le service async."""

    def get_or_create_user(self, user_id: int): ...
    def get_primary_company(self, user_id: int): ...
    def create_first_company(self, user_id: int, name: str, job_type: str): ...
    def get_or_create_player_actor(self, user_id: int): ...
    def get_or_create_and_refresh_mine(self, user_id: int): ...
    def collect_mine(self, user_id: int): ...
    def upgrade_mine(self, user_id: int, upgrade_type: str, request_id: str | None = None): ...
    def get_inventory(self, user_id: int): ...
    def create_market_order(self, user_id: int, side: str, resource_type: str,
                            quantity: int, unit_price: int, request_id: str): ...
    def cancel_market_order(self, user_id: int, order_id: int): ...
    def get_market_orders(self, user_id: int): ...
    def get_market_summary(self, resource_type: str, depth: int): ...
    def get_or_create_merchant(self, user_id: int): ...
    def upgrade_merchant(self, user_id: int, upgrade_type: str, request_id: str): ...
    def start_transport(self, user_id: int, receiver_user_id: int, resource_type: str,
                        quantity: int, request_id: str): ...
    def get_merchant_transports(self, user_id: int): ...
    def get_or_create_blacksmith(self, user_id: int): ...
    def start_forge_job(self, user_id: int, resource_type: str, quantity: int, request_id: str): ...
    def collect_forge_jobs(self, user_id: int, request_id: str): ...
    def upgrade_forge(self, user_id: int, upgrade_type: str, request_id: str): ...
    def get_forge_jobs(self, user_id: int): ...
    def create_ingot_shipment(self, user_id: int, merchant_id: int, banker_id: int,
                              quantity: int, request_id: str): ...
    def cancel_ingot_shipment(self, user_id: int, shipment_id: int, request_id: str): ...
    def accept_ingot_shipment(self, user_id: int, shipment_id: int, request_id: str): ...
    def get_or_create_banker(self, user_id: int): ...
    def sell_world_ingots(self, user_id: int, quantity: int, request_id: str): ...
    def get_world_market(self): ...
    def get_world_sales(self, user_id: int): ...
    def get_delivery_missions(self): ...
    def get_delivery_profile(self, user_id: int): ...
    def accept_delivery(self, user_id: int, mission_id: int, request_id: str): ...
    def create_contract(self, user_id: int, resource: str, quantity: int,
                        total: int, request_id: str): ...
    def accept_contract(self, user_id: int, contract_id: int, request_id: str): ...
    def cancel_contract(self, user_id: int, contract_id: int, request_id: str): ...
    def get_contracts(self, user_id: int, mine: bool): ...
    def record_activity(self, user_id: int): ...
    def evaluate_ai_companies(self): ...
    def purchase_ai_supply(self, user_id: int, resource_type: str,
                           quantity: int, request_id: str): ...
    def get_economy_stats(self): ...
    def get_admin_credit_stats(self): ...
    def adjust_admin_credits(self, admin_user_id: int, target_user_id: int,
                             operation: str, amount: int, request_id: str): ...


from economy_v2.sqlite_repository import SQLiteIndustrialEconomyRepository  # noqa: E402

__all__ = ["IndustrialEconomyRepository", "SQLiteIndustrialEconomyRepository"]
