from typing import Protocol


class IndustrialEconomyRepository(Protocol):
    """Contrat synchrone exécuté hors event loop par le service async."""

    def get_or_create_user(self, user_id: int): ...
    def get_primary_company(self, user_id: int): ...
    def create_first_company(self, user_id: int, name: str, job_type: str): ...
    def get_or_create_player_actor(self, user_id: int): ...
    def get_or_create_and_refresh_mine(self, user_id: int): ...
    def collect_mine(self, user_id: int): ...
    def upgrade_mine(self, user_id: int, upgrade_type: str, request_id: str | None = None): ...
    def get_inventory(self, user_id: int): ...
    def create_market_order(self, user_id: int, side: str, resource_type: str,
                            quantity: int, unit_price: int, request_id: str): ...
    def cancel_market_order(self, user_id: int, order_id: int): ...
    def get_market_orders(self, user_id: int): ...
    def get_market_summary(self, resource_type: str, depth: int): ...
    def get_or_create_merchant(self, user_id: int): ...
    def upgrade_merchant(self, user_id: int, upgrade_type: str, request_id: str): ...
    def start_transport(self, user_id: int, receiver_user_id: int, resource_type: str,
                        quantity: int, request_id: str): ...
    def get_merchant_transports(self, user_id: int): ...
    def get_or_create_blacksmith(self, user_id: int): ...
    def start_forge_job(self, user_id: int, resource_type: str, quantity: int, request_id: str): ...
    def collect_forge_jobs(self, user_id: int, request_id: str): ...
    def upgrade_forge(self, user_id: int, upgrade_type: str, request_id: str): ...
    def get_forge_jobs(self, user_id: int): ...
    def create_ingot_shipment(self, user_id: int, merchant_id: int, banker_id: int,
                              quantity: int, request_id: str): ...
    def cancel_ingot_shipment(self, user_id: int, shipment_id: int, request_id: str): ...
    def accept_ingot_shipment(self, user_id: int, shipment_id: int, request_id: str): ...
    def get_or_create_banker(self, user_id: int): ...
    def sell_world_ingots(self, user_id: int, quantity: int, request_id: str): ...
    def get_world_market(self): ...
    def get_world_sales(self, user_id: int): ...
    def get_delivery_missions(self): ...
    def get_delivery_profile(self, user_id: int): ...
    def accept_delivery(self, user_id: int, mission_id: int, request_id: str): ...
    def create_contract(self, user_id: int, resource: str, quantity: int,
                        total: int, request_id: str, target_user_id: int | None = None): ...
    def accept_contract(self, user_id: int, contract_id: int, request_id: str): ...
    def cancel_contract(self, user_id: int, contract_id: int, request_id: str): ...
    def get_contracts(self, user_id: int, mine: bool): ...
    def record_activity(self, user_id: int): ...
    def evaluate_ai_companies(self): ...
    def purchase_ai_supply(self, user_id: int, resource_type: str,
                           quantity: int, request_id: str): ...
    def get_economy_stats(self): ...
    def get_admin_credit_stats(self): ...
    def adjust_admin_credits(self, admin_user_id: int, target_user_id: int,
                             operation: str, amount: int, request_id: str): ...
    def get_next_actions_snapshot(self, user_id: int): ...
    def get_industrial_profile(self, user_id: int): ...
    def get_rankings(self, category: str, limit: int = 10): ...
    def refresh_achievements(self, user_id: int): ...
    def get_objectives(self, user_id: int, now: int | None = None): ...
    def get_player_stats(self, user_id: int): ...
    def get_orders_overview(self, user_id: int): ...
    def update_partnership(self, user_id: int, target_id: int, action: str, request_id: str): ...
    def get_partnerships(self, user_id: int): ...
    def get_notification_preferences(self, user_id: int): ...
    def set_notification_preference(self, user_id: int, category: str, enabled: bool): ...
    def enqueue_notification(self, user_id: int, event_type: str, event_key: str, payload=None): ...
    def get_admin_log(self, user_id: int, limit: int = 20): ...
    def economy_check(self): ...
    def get_season_dashboard(self, user_id: int, category: str = "overall", now: int | None = None): ...
    def get_season_history(self, limit: int = 10): ...
    def refresh_titles(self, user_id: int): ...
    def equip_title(self, user_id: int, selector: str, request_id: str): ...
    def remove_title(self, user_id: int, request_id: str): ...
    def get_active_events(self, now: int | None = None): ...
    def get_team(self, user_id: int): ...
    def invite_team_member(self, user_id: int, target_id: int, request_id: str): ...
    def resolve_team_invitation(self, user_id: int, invitation_id: int, action: str, request_id: str): ...
    def change_team(self, user_id: int, action: str, target_id: int | None, role: str | None, request_id: str): ...


from economy_v2.sqlite_repository import SQLiteIndustrialEconomyRepository  # noqa: E402

__all__ = ["IndustrialEconomyRepository", "SQLiteIndustrialEconomyRepository"]
